---
- name: Ensure apache is installed and started
  become: yes
  hosts: centos7

  tasks:
  - name: create couple of user for testing
    user:
      name: "{{ item }}"
      state: present
    with_items:
      - testuser1
      - testuser2